# file-format: 1.0.0
if(${CMAKE_BUILD_TYPE} STREQUAL "debug_GCC_NUCLEO-C542RC")
  set(CMSIS_Dclock 144000000)
  set(CMSIS_Dcore Cortex-M33)
  set(CMSIS_DcoreVersion r0p4)
  set(CMSIS_Ddsp DSP)
  set(CMSIS_Dendian Little-endian)
  set(CMSIS_Dfpu SP_FPU)
  set(CMSIS_Dmpu MPU)
  set(CMSIS_Dmve NO_MVE)
  set(CMSIS_Dname STM32C542RCT6)
  set(CMSIS_Dpacbti NO_PACBTI)
  set(CMSIS_Dsecure TZ-disabled)
  set(CMSIS_Dtz NO_TZ)
  set(CMSIS_Dvendor STMicroelectronics:13)
  set(CMSIS_Tcompiler GCC)
endif()

# Set target definition variables needed for the TOOLCHAIN_FILE
set(CPU ${CMSIS_Dcore})
set(FPU ${CMSIS_Dfpu})
set(DSP ${CMSIS_Ddsp})
set(MVE ${CMSIS_Dmve})
set(SECURE ${CMSIS_Dsecure})
