/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.11.0
 *
 * Project: 'board_t1.debug_GCC+NUCLEO-C542RC' 
 * Target:  'debug_GCC+NUCLEO-C542RC' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "stm32c5xx.h"

/* STMicroelectronics::Device:Startup@2.1.0 */
#define RTE_DEVICE_STARTUP_STM32C5XX    /* Device Startup for STM32C5 */


#endif /* RTE_COMPONENTS_H */
